# FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime
FROM dht-image-base

WORKDIR /app

# Copy the current directory contents into the container at /usr/src/app
COPY requirements.txt .

# Intstall packages
RUN apt update && apt install python3-opencv -y
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 5000
