FROM dht-image-base1

WORKDIR /app

# Copy the current directory contents into the container at /usr/src/app
COPY requirements.txt .

# Update pip and install packages
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
