FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime
# FROM dht-image-base

WORKDIR /app

# Copy the current directory contents into the container at /usr/src/app
COPY requirements.txt .

# Update pip and install packages
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install opencv-python

EXPOSE 5000
